onlyBuiltDependencies:
  - '-'
  - /
  - '@'
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@sentry-internal/node-cpu-profiler'
  - '@sentry/cli'
  - '@swc/core'
  - a
  - bcrypt
  - c
  - d
  - e
  - f
  - i
  - l
  - n
  - o
  - p
  - prisma
  - r
  - s
  - t
  - u
  - y
