export const APP_CONSTANTS = {
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  MIN_PAGE_SIZE: 1,
  DEFAULT_TIMEOUT: 30000, // 30 seconds
} as const;

// OTP Configuration - Phase 2
export const OTP_CONSTANTS = {
  /** OTP code length (6 digits) */
  CODE_LENGTH: 6,
  /** OTP expiration time in minutes */
  EXPIRY_MINUTES: 10,
  /** Maximum verification attempts before lockout */
  MAX_ATTEMPTS: 5,
  /** Reset token expiration in minutes (for password reset flow) */
  RESET_TOKEN_EXPIRY_MINUTES: 5,
} as const;

export const ERROR_CODES = {
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Authentication
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',

  // Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Resources
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT: 'CONFLICT',

  // Accounts Core
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_PROFILE_INCOMPATIBLE: 'ACCOUNT_PROFILE_INCOMPATIBLE',
  ACCOUNT_FIELD_IMMUTABLE: 'ACCOUNT_FIELD_IMMUTABLE',
  ACCOUNT_ALREADY_ARCHIVED: 'ACCOUNT_ALREADY_ARCHIVED',
  ACCOUNT_ALREADY_ACTIVE: 'ACCOUNT_ALREADY_ACTIVE',
  ACCOUNT_CURRENCY_UNSUPPORTED: 'ACCOUNT_CURRENCY_UNSUPPORTED',
  ACCOUNT_RECONCILIATION_NOT_FOUND: 'ACCOUNT_RECONCILIATION_NOT_FOUND',

  // Rate limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // OTP - Phase 2
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  AVATAR_FILE_NOT_FOUND: 'AVATAR_FILE_NOT_FOUND',

  // AI / Voucher Analyzer
  AI_EXECUTION_FAILED: 'AI_EXECUTION_FAILED',
  AI_RESPONSE_INVALID: 'AI_RESPONSE_INVALID',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
